In [1]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns
matplotlib.rcParams['figure.dpi'] = 100
from matplotlib import pyplot as plt

# Set Numpy to display floats with 3 decimal places
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [11]:
listofstringsagain = ['PaddleSS1.csv',
'PaddleSS2.csv',
'PaddleSS3.csv',
'PaddleSS4.csv',
'PaddleSS5.csv',
'HunterSS5.csv',
'TadaSS1.csv',
'TadaSS2.csv',
'TadaSS3.csv',
'TadaSS4.csv',
'TadaSS5.csv',
'HunterKothaCompSS5.csv',
'TadaKothaCompSS5.csv',
'HunterPaddleKothaCompSS1.csv',
'HunterPaddleKothaCompSS2.csv',
'HunterPaddleKothaCompSS3.csv',
'HunterPaddleKothaCompSS4.csv',
'HunterPaddleKothaCompSS5.csv',
                      
'HunterTadaKothaCompSS1.csv',
'HunterTadaKothaCompSS2.csv',
'HunterTadaKothaCompSS3.csv',
'HunterTadaKothaCompSS4.csv',
'HunterTadaKothaCompSS5.csv',
                      
'HunterTadaPaddleKothaCompSS1.csv',
'HunterTadaPaddleKothaCompSS2.csv',
'HunterTadaPaddleKothaCompSS3.csv',
'HunterTadaPaddleKothaCompSS4.csv',
'HunterTadaPaddleKothaCompSS5.csv',
                      
'HunterTadaPaddleSS1.csv',
'HunterTadaPaddleSS2.csv',
'HunterTadaPaddleSS3.csv',
'HunterTadaPaddleSS4.csv',
'HunterTadaPaddleSS5.csv',
                      
'TadaPaddleKothaCompSS1.csv',
'TadaPaddleKothaCompSS2.csv',
'TadaPaddleKothaCompSS3.csv',
'TadaPaddleKothaCompSS4.csv',
'TadaPaddleKothaCompSS5.csv']

In [16]:
df = pd.read_csv('remainingv1.csv')

df = df[df['Is_A_Duplicate'] == False]
df = df[df['Origin'] == 'PaddleSS1.csv']
df

,Unnamed: 0,Seq,Origin,Distance,Is_A_Duplicate
234652,3,SNSEDSSAVFDFDDQSNESYGFDYLDTDESLSQVSIDDRS,PaddleSS1.csv,PaddleSS1.csv,False
234665,16,ELEDEWDEDVESIDQDVLSNSLFMESTESQIDIYEMNSEE,PaddleSS1.csv,PaddleSS1.csv,False
234682,33,DCYWSMDDFESFDDEEEKNWDSLKIALDNQTEDQEDLESD,PaddleSS1.csv,PaddleSS1.csv,False
234714,65,FLDAFSQDWADSQTPLSWIETLSGDQFGSDNSLQESSFNN,PaddleSS1.csv,PaddleSS1.csv,False
234738,89,DLASWDISFDGEEGYELNSRSDSEDWDQMIEDMTSSNEAK,PaddleSS1.csv,PaddleSS1.csv,False
...,...,...,...,...,...
235635,986,QVPIEHHLITISDDPFMSVFLQQEEEWEDLVLGRRATQKP,PaddleSS1.csv,PaddleSS1.csv,False
235639,990,ATDENDYFLFVEMSPGYTQEGGGGSEGTIYMNAMDHQQVS,PaddleSS1.csv,PaddleSS1.csv,False
235643,994,SRPSNNGAAVLYISDDPPLDWLDVYDAMAQQFTYAVANTP,PaddleSS1.csv,PaddleSS1.csv,False
235644,995,VADMDLDPPVRPGGTDLHNPEINIWEVDWYNSSNQNTWYG,PaddleSS1.csv,PaddleSS1.csv,False
235647,998,EYEDIWYWSSEENEFKSPVWKTVDQIITNGNYFNDGNGLA,PaddleSS1.csv,PaddleSS1.csv,False

In [20]:
df = pd.read_csv('remainingv1.csv')

def removerv1(string, dummydf):
    counter = 250
    
    unique1 = dummydf[dummydf['Origin'] == string]    
    unique = unique1[unique1['Is_A_Duplicate'] == False]
    counter = counter - len(unique)

    temp = unique['Seq']
    minusunique = dummydf[~dummydf['Seq'].isin(temp)]
        
    parttwo = minusunique[minusunique['Origin'] == (string)]
    pack250 = pd.concat([unique, parttwo[:counter]], ignore_index=True)    
    pack250.to_csv('YX_250'+string)
    
    justtocountstringdf = dummydf[dummydf['Origin'] == (string)]
    
    print(len(pack250))
    print(len(unique1))
    print(len(parttwo))
    print('border')
    return minusunique[~minusunique['Seq'].isin(parttwo[:counter]['Seq'])]

for i in listofstringsagain:
    df = removerv1(i,df)

250
1000
789
border
250
1000
808
border
250
1000
810
border
250
1000
813
border
250
1000
812
border
250
953
802
border
250
971
877
border
250
955
875
border
250
948
860
border
250
949
884
border
250
848
789
border
250
1876
1767
border
250
2033
1931
border
250
2000
2000
border
250
2832
2832
border
250
3425
3425
border
250
4473
4473
border
250
1367
1367
border
250
2059
2059
border
250
2779
2779
border
250
3465
3465
border
250
4459
4459
border
250
1122
1122
border
250
1332
1332
border
250
2019
2019
border
250
2614
2614
border
250
3549
3549
border
250
765
765
border
250
1972
1972
border
250
3079
3079
border
250
4149
4149
border
250
5607
5607
border
250
1278
1278
border
250
1762
1762
border
250
2558
2558
border
250
3310
3310
border
250
4433
4433
border
250
920
920
border

In [6]:
#lengths of each
templist1 = []
for i in filelistnormal:
    temp = len(pd.read_csv(i))
    templist1.append(temp)

#orgins
newlist = []
for i in range(len(filelistnormal)):
    newlist = newlist + ([filelistnormal[i]]*templist1[i])
    
#making copy of just seqs
dummydf = pd.DataFrame(columns=['Seq'])
for i in filelistnormal:
    temp = pd.read_csv(i)[['Seq']]
    dummydf = pd.concat([dummydf,temp])

#collect dups
dups = dummydf.duplicated(keep = False)

#collect distances
distances = pd.DataFrame(columns=['Distance'])
for i in filelistnormal:
    temp = pd.read_csv(i)[['Distance']]
    distances = pd.concat([distances,temp])

dummydf['Origin'] = newlist
dummydf['Distance'] = newlist
dummydf['Is_A_Duplicate'] = dups

In [32]:
temp1 = pd.DataFrame() 
for i in checkin:
    temp  = pd.read_csv(i)
    temp1 = pd.concat([temp1,temp[['Seq']]])
temp1

                                          Seq
0    MLDEEGLLLDEDTEVFSTAEAVSDEEALEDLFNSQNLMSP
1    CFALFSDEDELEDDSDIEEISESFWAMELRMNLESLDTIL
2    RTDLHFDLQEEVDIGLDSFEADILDFAKTDKEFQSLLVKG
3    LDRLKELDDFDDHLLSSDVDEDSACYDFTFGLCFSKLFDG
4    SDEQLELSEKQSYSDLDYKAEGLDSFPDAVQLWFPFLLDI
..                                        ...
245  IDHPSSSSMLSGELLFDGCWLETTDGSEFLSTNSDYDIGI
246  WSSVTSFVSPDESFFNVSAFSEDEWIEVDSDEDKMLVGDV
247  VKLFLCSDDDLFSAYMNLDNIDHLLDFSSLDPSNYNNMWN
248  NQEYKKGLWTVEEDLEWLSNFVEDSFSDDTDEDLYKYDPW
249  MVLSSSDNEDEDVSRYDLKYLDDDQEWVLLTCEADLEECI

[18750 rows x 1 columns]

In [34]:
temp1 = pd.DataFrame() 
for i in checkin:
    temp  = pd.read_csv(i)
    temp1 = pd.concat([temp1,temp[['Score']]])
temp1

KeyError: "None of [Index(['Score'], dtype='object')] are in the [columns]"

In [ ]:
plt.hist(data)

In [33]:
temp1dups = temp1.duplicated().sum()
temp1dups

0

In [31]:
checkin = ['X_250HunterKothaCompSS1.csv',
'X_250HunterKothaCompSS2.csv',
'X_250HunterKothaCompSS3.csv',
'X_250HunterKothaCompSS4.csv',
'YX_250HunterKothaCompSS5.csv',

'X_250HunterPaddleSS1.csv',
'X_250HunterPaddleSS2.csv',
'X_250HunterPaddleSS3.csv',
'X_250HunterPaddleSS4.csv',
'X_250HunterPaddleSS5.csv',
    
'X_250HunterSS1.csv',
'X_250HunterSS2.csv',
'X_250HunterSS3.csv',
'X_250HunterSS4.csv',
'YX_250HunterSS5.csv',
    
'X_250HunterTadaSS1.csv',
'X_250HunterTadaSS2.csv',
'X_250HunterTadaSS3.csv',
'X_250HunterTadaSS4.csv',
'X_250HunterTadaSS5.csv',
    
'X_250KothaCompSS1normal.csv',
'X_250KothaCompSS2normal.csv',
'X_250KothaCompSS3normal.csv',
'X_250KothaCompSS4normal.csv',
'X_250KothaCompSS5normal.csv',
    
'X_250PaddleKothaCompSS1.csv',
'X_250PaddleKothaCompSS2.csv',
'X_250PaddleKothaCompSS3.csv',
'X_250PaddleKothaCompSS4.csv',
'X_250PaddleKothaCompSS5.csv',
    
'X_250TadaKothaCompSS1.csv',
'X_250TadaKothaCompSS2.csv',
'X_250TadaKothaCompSS3.csv',
'X_250TadaKothaCompSS4.csv',
'YX_250TadaKothaCompSS5.csv',
    
'X_250TadaPaddleSS1.csv',
'X_250TadaPaddleSS2.csv',
'X_250TadaPaddleSS3.csv',
'X_250TadaPaddleSS4.csv',
'X_250TadaPaddleSS5.csv',
    
'YX_250HunterPaddleKothaCompSS1.csv',
'YX_250HunterPaddleKothaCompSS2.csv',
'YX_250HunterPaddleKothaCompSS3.csv',
'YX_250HunterPaddleKothaCompSS4.csv',
'YX_250HunterPaddleKothaCompSS5.csv',
    
'YX_250HunterTadaKothaCompSS1.csv',
'YX_250HunterTadaKothaCompSS2.csv',
'YX_250HunterTadaKothaCompSS3.csv',
'YX_250HunterTadaKothaCompSS4.csv',
'YX_250HunterTadaKothaCompSS5.csv',
    
'YX_250HunterTadaPaddleKothaCompSS1.csv',
'YX_250HunterTadaPaddleKothaCompSS2.csv',
'YX_250HunterTadaPaddleKothaCompSS3.csv',
'YX_250HunterTadaPaddleKothaCompSS4.csv',
'YX_250HunterTadaPaddleKothaCompSS5.csv',
    
'YX_250HunterTadaPaddleSS1.csv',
'YX_250HunterTadaPaddleSS2.csv',
'YX_250HunterTadaPaddleSS3.csv',
'YX_250HunterTadaPaddleSS4.csv',
'YX_250HunterTadaPaddleSS5.csv',
    
'YX_250PaddleSS1.csv',
'YX_250PaddleSS2.csv',
'YX_250PaddleSS3.csv',
'YX_250PaddleSS4.csv',
'YX_250PaddleSS5.csv',
    

'YX_250TadaPaddleKothaCompSS1.csv',
'YX_250TadaPaddleKothaCompSS2.csv',
'YX_250TadaPaddleKothaCompSS3.csv',
'YX_250TadaPaddleKothaCompSS4.csv',
'YX_250TadaPaddleKothaCompSS5.csv',
    
'YX_250TadaSS1.csv',
'YX_250TadaSS2.csv',
'YX_250TadaSS3.csv',
'YX_250TadaSS4.csv',
'YX_250TadaSS5.csv']

In [ ]:
def removerv1(strings, dummydf):
    counter = 250
    exp1 = dummydf[dummydf['Origin'] == (string)]
    tempexp1 = exp1[exp1['Is_A_Duplicate'] == False]
    counter = len(tempexp1) - counter

    temp = tempexp1['Seq']
    dummydf = dummydf[~dummydf['Seq'].isin(temp)]
    
    tempexp1.concat()
    pd.concat([tempexp1, dummydf[dummydf['Origin'] == (string)][:counter]], ignore_index=True)    
    
    tempexp1.to_csv('X_250'+string)
    return dummydf

def imlazy(string, dummydf):
    exp1 = dummydf[dummydf['Origin'] == (string)]
    tempexp1 = exp1[exp1['Is_A_Duplicate'] == False]
    tempexp1 = tempexp1[:250].drop(['Is_A_Duplicate'], axis =1)
    tempexp1.to_csv('X_250'+string)
    return tempexp1

In [8]:
def remover(string, dummydf):
    exp1 = dummydf[dummydf['Origin'] == (string)]
    tempexp1 = exp1[exp1['Is_A_Duplicate'] == False]
    tempexp1 = tempexp1[:250]#.drop(['Is_A_Duplicate'], axis =1)
    tempexp1.to_csv('X_250'+string)

    firstlength = len(dummydf)
    temp = tempexp1['Seq']
    dummydf = dummydf[~dummydf['Seq'].isin(temp)]
    finallength = len(dummydf)
    exp1 = dummydf[dummydf['Origin'] == (string)]
    print('length of remaining combination' + str(len(exp1)))
    #print('started at ' + str(firstlength) + ' ending at ' + str(finallength))
    return dummydf

In [9]:
#dummydf = remover(imlazy('KothaCompSS1normal.csv', dummydf),dummydf)

for i in dummytemplist:
    dummydf = remover(i,dummydf)

length of remaining combination8724
length of remaining combination7112
length of remaining combination5614
length of remaining combination6951
length of remaining combination7849
length of remaining combination4789
length of remaining combination5443
length of remaining combination3745
length of remaining combination4098
length of remaining combination5991
length of remaining combination8378
length of remaining combination4767
length of remaining combination6436
length of remaining combination3316
length of remaining combination5103
length of remaining combination750
length of remaining combination5159
length of remaining combination4318
length of remaining combination6337
length of remaining combination750
length of remaining combination3674
length of remaining combination3695
length of remaining combination2513
length of remaining combination3373
length of remaining combination750
length of remaining combination4325
length of remaining combination750
length of remaining combination750
length of remaining combination5395
length of remaining combination750
length of remaining combination750
length of remaining combination3084
length of remaining combination2729
length of remaining combination2747
length of remaining combination750
length of remaining combination750
length of remaining combination2726

In [15]:
dummydf.to_csv('remainingv1.csv')

In [13]:
fwoowgnowng = ['HunterKothaCompSS5.csv','TadaKothaCompSS5.csv']

In [14]:
for i in fwoowgnowng:
    print(len(dummydf[dummydf['Origin'] == (i)]))

2071
2415

In [5]:
dummytemplist = ['HunterTadaSS4.csv',
'HunterTadaSS3.csv', 
'HunterTadaSS2.csv',  
'PaddleKothaCompSS4.csv', 
'HunterPaddleSS4.csv',  
'PaddleKothaCompSS2.csv',
'PaddleKothaCompSS3.csv',  
'PaddleKothaCompSS1.csv',  
'HunterTadaSS1.csv', 
'HunterPaddleSS3.csv', 
'TadaPaddleSS4.csv', 
'HunterPaddleSS2.csv',
'TadaPaddleSS3.csv', 
'HunterPaddleSS1.csv', 
'TadaPaddleSS2.csv', 
'KothaCompSS1normal.csv',  
'TadaKothaCompSS3.csv',  
'TadaKothaCompSS2.csv',  
'TadaKothaCompSS4.csv',  
'KothaCompSS2normal.csv',  
'HunterKothaCompSS2.csv',  
'TadaPaddleSS1.csv', 
'PaddleKothaCompSS5.csv',  
'TadaKothaCompSS1.csv',  
'KothaCompSS3normal.csv',  
'HunterKothaCompSS3.csv',  
'HunterSS1.csv', 
'KothaCompSS4normal.csv',  
'HunterKothaCompSS4.csv',  
'KothaCompSS5normal.csv',  
'HunterSS2.csv', 
'TadaPaddleSS5.csv', 
'HunterPaddleSS5.csv', 
'HunterTadaSS5.csv', 
'HunterSS4.csv', 
'HunterSS3.csv', 
'HunterKothaCompSS1.csv']

In [4]:
filelist250 = ['final250HunterKothaCompSS1.csv',
'final250HunterKothaCompSS2.csv',
'final250HunterKothaCompSS3.csv',
'final250HunterKothaCompSS4.csv',
'final250HunterKothaCompSS5.csv',
'final250HunterPaddleKothaCompSS1.csv',
'final250HunterPaddleKothaCompSS2.csv',
'final250HunterPaddleKothaCompSS3.csv',
'final250HunterPaddleKothaCompSS4.csv',
'final250HunterPaddleKothaCompSS5.csv',
'final250HunterPaddleSS1.csv',
'final250HunterPaddleSS2.csv',
'final250HunterPaddleSS3.csv',
'final250HunterPaddleSS4.csv',
'final250HunterPaddleSS5.csv',
'final250HunterSS1.csv',
'final250HunterSS2.csv',
'final250HunterSS3.csv',
'final250HunterSS4.csv',
'final250HunterSS5.csv',
'final250HunterTadaKothaCompSS1.csv',
'final250HunterTadaKothaCompSS2.csv',
'final250HunterTadaKothaCompSS3.csv',
'final250HunterTadaKothaCompSS4.csv',
'final250HunterTadaKothaCompSS5.csv',
'final250HunterTadaPaddleKothaCompSS1.csv',
'final250HunterTadaPaddleKothaCompSS2.csv',
'final250HunterTadaPaddleKothaCompSS3.csv',
'final250HunterTadaPaddleKothaCompSS4.csv',
'final250HunterTadaPaddleKothaCompSS5.csv',
'final250HunterTadaPaddleSS1.csv',
'final250HunterTadaPaddleSS2.csv',
'final250HunterTadaPaddleSS3.csv',
'final250HunterTadaPaddleSS4.csv',
'final250HunterTadaPaddleSS5.csv',
'final250HunterTadaSS1.csv',
'final250HunterTadaSS2.csv',
'final250HunterTadaSS3.csv',
'final250HunterTadaSS4.csv',
'final250HunterTadaSS5.csv',
'final250KothaCompSS1_v1.csv',
'final250KothaCompSS2_v1.csv',
'final250KothaCompSS3_v1.csv',
'final250KothaCompSS4_v1.csv',
'final250KothaCompSS5_v1.csv',
'final250PaddleKothaCompSS1.csv',
'final250PaddleKothaCompSS2.csv',
'final250PaddleKothaCompSS3.csv',
'final250PaddleKothaCompSS4.csv',
'final250PaddleKothaCompSS5.csv',
'final250PaddleSS1.csv',
'final250PaddleSS2.csv',
'final250PaddleSS3.csv',
'final250PaddleSS4.csv',
'final250PaddleSS5.csv',
'final250TadaKothaCompSS1.csv',
'final250TadaKothaCompSS2.csv',
'final250TadaKothaCompSS3.csv',
'final250TadaKothaCompSS4.csv',
'final250TadaKothaCompSS5.csv',
'final250TadaPaddleKothaCompSS1.csv',
'final250TadaPaddleKothaCompSS2.csv',
'final250TadaPaddleKothaCompSS3.csv',
'final250TadaPaddleKothaCompSS4.csv',
'final250TadaPaddleKothaCompSS5.csv',
'final250TadaPaddleSS1.csv',
'final250TadaPaddleSS2.csv',
'final250TadaPaddleSS3.csv',
'final250TadaPaddleSS4.csv',
'final250TadaPaddleSS5.csv',
'final250TadaSS1.csv',
'final250TadaSS2.csv',
'final250TadaSS3.csv',
'final250TadaSS4.csv',
'final250TadaSS5.csv']

In [4]:
filelistnormal = ['HunterKothaCompSS1.csv',
'HunterKothaCompSS2.csv',
'HunterKothaCompSS3.csv',
'HunterKothaCompSS4.csv',
'HunterKothaCompSS5.csv',
'HunterPaddleKothaCompSS1.csv',
'HunterPaddleKothaCompSS2.csv',
'HunterPaddleKothaCompSS3.csv',
'HunterPaddleKothaCompSS4.csv',
'HunterPaddleKothaCompSS5.csv',
'HunterPaddleSS1.csv',
'HunterPaddleSS2.csv',
'HunterPaddleSS3.csv',
'HunterPaddleSS4.csv',
'HunterPaddleSS5.csv',
'HunterTadaKothaCompSS1.csv',
'HunterTadaKothaCompSS2.csv',
'HunterTadaKothaCompSS3.csv',
'HunterTadaKothaCompSS4.csv',
'HunterTadaKothaCompSS5.csv',
'HunterTadaPaddleKothaCompSS1.csv',
'HunterTadaPaddleKothaCompSS2.csv',
'HunterTadaPaddleKothaCompSS3.csv',
'HunterTadaPaddleKothaCompSS4.csv',
'HunterTadaPaddleKothaCompSS5.csv',
'HunterTadaPaddleSS1.csv',
'HunterTadaPaddleSS2.csv',
'HunterTadaPaddleSS3.csv',
'HunterTadaPaddleSS4.csv',
'HunterTadaPaddleSS5.csv',
'HunterTadaSS1.csv',
'HunterTadaSS2.csv',
'HunterTadaSS3.csv',
'HunterTadaSS4.csv',
'HunterTadaSS5.csv',
'PaddleKothaCompSS1.csv',
'PaddleKothaCompSS2.csv',
'PaddleKothaCompSS3.csv',
'PaddleKothaCompSS4.csv',
'PaddleKothaCompSS5.csv',
'TadaKothaCompSS1.csv',
'TadaKothaCompSS2.csv',
'TadaKothaCompSS3.csv',
'TadaKothaCompSS4.csv',
'TadaKothaCompSS5.csv',
'TadaPaddleKothaCompSS1.csv',
'TadaPaddleKothaCompSS2.csv',
'TadaPaddleKothaCompSS3.csv',
'TadaPaddleKothaCompSS4.csv',
'TadaPaddleKothaCompSS5.csv',
'TadaPaddleSS1.csv',
'TadaPaddleSS2.csv',
'TadaPaddleSS3.csv',
'TadaPaddleSS4.csv',
'TadaPaddleSS5.csv',
'TadaSS1.csv',
'TadaSS2.csv',
'TadaSS3.csv',
'TadaSS4.csv',
'TadaSS5.csv',
'HunterSS1.csv',
'HunterSS2.csv',
'HunterSS3.csv',
'HunterSS4.csv',
'HunterSS5.csv',
'PaddleSS1.csv',
'PaddleSS2.csv',
'PaddleSS3.csv',
'PaddleSS4.csv',
'PaddleSS5.csv',
'KothaCompSS1normal.csv',
'KothaCompSS2normal.csv',
'KothaCompSS3normal.csv',
'KothaCompSS4normal.csv',
'KothaCompSS5normal.csv']